FROM node:16.16.0-alpine3.15

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm ci
RUN npm install -g serve

COPY . ./

RUN npm run build

CMD serve -s ./build
